query getNotes($filter: FiltersExpression) {
    notes(filter: $filter) {
        note { 
            _id
            title
            body
            isFeatured
            user {
                _id
                name
                email
            }
            createdAt
            updatedAt
        }
        currentPage
        totalPages
        message
    }
}